/*
 * Swagger Song Demo
 * Sample Swagger Demo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.sample.ms.application.model;

import java.util.Objects;

/**
 * Song
 */
public class Song {
	private Integer customerId;
	private Integer id;
	private String songName = null;
	private String singerName = null;
	private String releaseDate = null;

	public Song() {

	}

	public Song(Integer customerId, Integer id, String songName, String singerName, String releaseDate) {
		super();
		this.customerId = customerId;
		this.id = id;
		this.songName = songName;
		this.singerName = singerName;
		this.releaseDate = releaseDate;
	}

	public Song(Integer id, String songName, String singerName, String releaseDate) {
		super();
		this.id = id;
		this.songName = songName;
		this.singerName = singerName;
		this.releaseDate = releaseDate;
	}

/**
   * Get customerId
   * @return customerId
  **/
  public Integer getCustomerId() {
    return customerId;
  }

  public void setCustomerId(Integer customerId) {
    this.customerId = customerId;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

   /**
   * Song Name
   * @return songName
  **/
  public String getSongName() {
    return songName;
  }

  public void setSongName(String songName) {
    this.songName = songName;
  }

   /**
   * Singer Name
   * @return singerName
  **/
  public String getSingerName() {
    return singerName;
  }

  public void setSingerName(String singerName) {
    this.singerName = singerName;
  }

   /**
   * Release Date
   * @return releaseDate
  **/
  public String getReleaseDate() {
    return releaseDate;
  }

  public void setReleaseDate(String releaseDate) {
    this.releaseDate = releaseDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Song song = (Song) o;
    return Objects.equals(this.customerId, song.customerId) &&
        Objects.equals(this.id, song.id) &&
        Objects.equals(this.songName, song.songName) &&
        Objects.equals(this.singerName, song.singerName) &&
        Objects.equals(this.releaseDate, song.releaseDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerId, id, songName, singerName, releaseDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Song {\n");
    
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    songName: ").append(toIndentedString(songName)).append("\n");
    sb.append("    singerName: ").append(toIndentedString(singerName)).append("\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

